#! /bin/sh

# Brahms Setup
export BRAHMS_ROOT=/Applications/Brahms/AgentEnvironment

# Java Setup

#export JAVA_MEMORY="-Xincgc -Xmx4096m -Xss8192k -Xms4096m"
export JAVA_MEMORY="-Xmx4096m -Xss8192k -Xms4096m -XX:-UseGCOverheadLimit"
export BOOTCP=-Xbootclasspath/p:"$BRAHMS_ROOT/lib/jacorb/jacorb.jar":"$BRAHMS_ROOT/lib/jacorb/logkit-1.2.jar":"$BRAHMS_ROOT/lib/jacorb/avalon-framework-4.1.5.jar"
export CP="$BRAHMS_ROOT/config:$BRAHMS_ROOT/deploy:$BRAHMS_ROOT/Agents:$CP"
export EXT_JAR_DIRS="/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/ext":"$BRAHMS_ROOT/lib":"$BRAHMS_ROOT/lib/apache":"$BRAHMS_ROOT/lib/ci":"$BRAHMS_ROOT/lib/jacorb":"$BRAHMS_ROOT/lib/jidesoft":"$BRAHMS_ROOT/lib/mysql":"$BRAHMS_ROOT/lib/nss":"$BRAHMS_ROOT/deploy":"$EXT_JAR_DIRS"
export ORB="-Dorg.omg.CORBA.ORBClass=org.jacorb.orb.ORB -Dorg.omg.CORBA.ORBSingletonClass=org.jacorb.orb.ORBSingleton"
export JAVA_PROPERTIES="$JAVA_MEMORY $BOOTCP -cp $CP -Djava.ext.dirs=$EXT_JAR_DIRS $ORB"

#echo java $JAVA_PROPERTIES gov.nasa.arc.brahms.vm.bvm $@
java $JAVA_PROPERTIES -ea gov.nasa.arc.brahms.vm.bvm $@
